### ISSUE TITLE
Problem install sikulpy on windows

### ISSUE THREAD

**Issue by wolfc01** [shish/sikulpy#15]
Hello,

I installed all dependencies but found following problems:

C:\Users\carl\Desktop\sikulpy>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from sikuli.version import VERSION
  File "C:\Users\carl\Desktop\sikulpy\sikuli\__init__.py", line 2, in <module>
    from .script import *
  File "C:\Users\carl\Desktop\sikulpy\sikuli\script\__init__.py", line 4, in <module>
    from .app import App
  File "C:\Users\carl\Desktop\sikulpy\sikuli\script\app.py", line 3, in <module>
    from .region import Region
  File "C:\Users\carl\Desktop\sikulpy\sikuli\script\region.py", line 13, in <module>
    from .settings import Settings
  File "C:\Users\carl\Desktop\sikulpy\sikuli\script\settings.py", line 23
SyntaxError: Non-ASCII character '\xe2' in file C:\Users\carl\Desktop\sikulpy\sikuli\script\settings.py on line 23, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

my environment is python 2.7, on windows7.

Any clue?

Best regards
Carl.

**Comment by shish** [comment]
Looks like a UTF8 character got copy-pasted into one of the documentation comments; I've removed that, so hopefully things work now :)
