### ISSUE TITLE
import sikuli fails on python 2.7.13 windows7

### ISSUE THREAD

**Issue by wolfc01** [shish/sikulpy#17]
Hello Shish,

import sikuli fails on python 2.7.13, see below
```
C:\Users\cn\Desktop\sikulpy_prereqs\sikulpy-master>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sikuli
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sikuli\__init__.py", line 2, in <module>
    from .script import *
  File "sikuli\script\__init__.py", line 17, in <module>
    desktop = Screen(0)
  File "sikuli\script\screen.py", line 19, in __init__
    super().__init__(Rectangle(x, y, w, h))
TypeError: super() takes at least 1 argument (0 given)
```
Best regards
Carl.

**Comment by shish** [comment]
Just ran into that while testing 2.7 myself, should be fixed now :)

**Comment by shish** [comment]
I've set up continuous testing; there's not a lot of coverage yet, but it makes sure that the code loads at least - currently passing with 2.7 (failing on 3.5 because there aren't nice python3-opencv packages)

https://travis-ci.org/shish/sikulpy
